### Global Findex Dataset Thailand EDA 
Thailand's Financial and Digital Financial Inclusion: A Comparative Analysis of Global Findex 2021 and 2024

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

sns.set(style="whitegrid", context="notebook") 
plt.rcParams['figure.dpi'] = 100 
pd.set_option('display.max_columns', 12)
pd.set_option('display.max_rows', 12)

df1 = pd.read_csv(
    'Findex Raw data_2021 (0521-0223).csv',
    encoding='latin1'
)

df2 = pd.read_csv(
    'Findex Raw Data_2025 (0524-1224).csv',
    encoding='latin1'
)
print(df1.shape)
print(df2.shape)

(143887, 128)
(144090, 199)

In [14]:
df1.head()

,economy,economycode,regionwb,pop_adult,wpid_random,wgt,...,remittances,mobileowner,internetaccess,anydigpayment,merchantpay_dig,year
0,Afghanistan,AFG,South Asia,22647496.0,144274031,0.716416,...,5.0,1,2,1,0.0,2021
1,Afghanistan,AFG,South Asia,22647496.0,180724554,0.497408,...,5.0,1,2,0,0.0,2021
2,Afghanistan,AFG,South Asia,22647496.0,130686682,0.650431,...,3.0,2,2,0,0.0,2021
3,Afghanistan,AFG,South Asia,22647496.0,142646649,0.991862,...,5.0,1,2,0,0.0,2021
4,Afghanistan,AFG,South Asia,22647496.0,199055310,0.554940,...,5.0,2,2,0,0.0,2021

In [15]:
df2.head()

,year,economy,economycode,regionwb,pop_adult,wpid_random,...,fin49c,fin49d,fin49e,fin49f,fin50,fin51
0,2024,Nicaragua,NIC,Latin America & Caribbean (excluding high income),4830854,111111345,...,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,Costa Rica,CRI,Latin America & Caribbean (excluding high income),4118576,111111579,...,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,Mali,MLI,Sub-Saharan Africa (excluding high income),12725942,111112511,...,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Kuwait,KWT,High income,3950546,111113432,...,NaN,NaN,NaN,NaN,1.0,1.0
4,2024,Turkiye,TUR,Europe & Central Asia (excluding high income),66691005,111115194,...,NaN,NaN,NaN,NaN,1.0,2.0

### EDA for Findex_dataset Thailand 2021 and 2024

In [3]:
print(df1.columns.to_list())
print(df2.columns.to_list())

['economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity_f2f', 'account', 'account_fin', 'account_mob', 'fin1_1a', 'fin1_1b', 'fin2', 'fin4', 'fin4a', 'fin5', 'fin6', 'fin7', 'fin8', 'fin8a', 'fin8b', 'fin9', 'fin9a', 'fin10', 'fin10_1a', 'fin10_1b', 'fin10_1c', 'fin10_1d', 'fin10_1e', 'fin10a', 'fin10b', 'fin11_1', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin11g', 'fin11h', 'fin13_1a', 'fin13_1b', 'fin13_1c', 'fin13_1d', 'fin13_1e', 'fin13_1f', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin14_1', 'fin14_2', 'fin14_2_China', 'fin14a', 'fin14a1', 'fin14b', 'fin14c', 'fin14c_2', 'fin14c_2_China', 'fin16', 'fin17a', 'fin17a1', 'fin17b', 'fin20', 'fin22a', 'fin22b', 'fin22c', 'fin24', 'fin24a', 'fin24b', 'fin26', 'fin27_1', 'fin27c1', 'fin27c2', 'fin28', 'fin29_1', 'fin29c1', 'fin29c2', 'fin30', 'fin31a', 'fin31b', 'fin31b1', 'fin31b1_China', 'fin31c', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34d', 'fin34e', 'fin35', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39d', 'fin39e', 'fin42', 'fin42a', 'fin43a', 'fin43b', 'fin43d', 'fin43e', 'fin44a', 'fin44b', 'fin44c', 'fin44d', 'fin45', 'fin45_1', 'fin45_1_China', 'saved', 'borrowed', 'receive_wages', 'receive_transfers', 'receive_pension', 'receive_agriculture', 'pay_utilities', 'remittances', 'mobileowner', 'internetaccess', 'anydigpayment', 'merchantpay_dig', 'year']
['year', 'economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity', 'account_fin', 'account_mob', 'account', 'dig_account', 'borrowed', 'saved', 'receive_wages', 'receive_transfers', 'receive_pensions', 'receive_agriculture', 'merchantpay_dig', 'pay_utilities', 'domestic_remittances', 'anydigpayment', 'fin2', 'fin3', 'fin4', 'fin5', 'fin6', 'fin7', 'fin8', 'fin9a', 'fin9b', 'fin10', 'fin11_0', 'fin11_1', 'fin11_2', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin13_1', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin13e', 'fin13f', 'fin13f_1', 'fin14a', 'fin14b', 'fin14c', 'fin14d', 'fin14e', 'fin15', 'fin16', 'fin17a', 'fin17b', 'fin17c', 'fin17d', 'fin17e', 'fin17f', 'fin18', 'fin19', 'fin20', 'fin21', 'fin22a', 'fin22a_1', 'fin22b', 'fin22c', 'fin22d', 'fin22e', 'fin22f', 'fin22g', 'fin22h', 'fin23', 'fin24', 'fin24a', 'fin24b', 'fin24c', 'fin24d1', 'fin24d2', 'fin24d3', 'fin25e1', 'fin25e2', 'fin25e3', 'fin25e4', 'fin26a', 'fin26b', 'fin27', 'fh1', 'fin28', 'fh2', 'fin29', 'fh2a', 'fin30', 'fin31a', 'fin31b', 'fin31c', 'fin31d', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34c', 'fin34d', 'fin35', 'fin36', 'fin36a', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39c', 'fin39d', 'fin40', 'fin41', 'fin41a', 'fin42', 'fin43a', 'fin43b', 'fin43c', 'fin43d', 'fin44', 'fin45', 'internet_use', 'con1', 'con2a', 'con2b', 'con2c', 'con2d', 'con2e', 'con2f', 'con2g', 'con3', 'con4', 'con5', 'con6', 'con7', 'con8', 'con9', 'con10', 'con11', 'con12', 'con13', 'con14', 'con15', 'con16', 'con17', 'con18', 'con19', 'con20', 'con21', 'con22', 'con23', 'con24', 'con25', 'con26', 'con27', 'con28', 'con29', 'con30a', 'con30b', 'con30c', 'con30d', 'con30e', 'con30f', 'con30g', 'con30h', 'con31a', 'con31b', 'con31c', 'con31d', 'con31e', 'con31f', 'con31g', 'con31h', 'con32', 'fin46', 'fin47', 'fin48a', 'fin48b', 'fin48c', 'fin48d', 'fin48e', 'fin48f', 'fin49a', 'fin49b', 'fin49c', 'fin49d', 'fin49e', 'fin49f', 'fin50', 'fin51']

In [4]:
# Select Thailand economic data from both datasets 
df1_thailand = df1[df1['economy'] == 'Thailand'].copy()
df2_thailand = df2[df2['economy'] == 'Thailand'].copy() 
print(df1_thailand.shape)
print(df2_thailand.shape)

(1017, 128)
(1000, 199)

In [5]:
# print(df1_thailand['year'].value_counts())
# print(df2_thailand['year'].value_counts())

In [6]:
print(set(df1_thailand.columns) - set(df2_thailand.columns))

{'fin13_1a', 'fin27c2', 'urbanicity_f2f', 'internetaccess', 'fin10b', 'fin10_1b', 'fin45_1_China', 'receive_pension', 'fin10_1a', 'fin44d', 'fin34e', 'fin29c1', 'fin39e', 'fin13_1b', 'fin27_1', 'fin14_1', 'fin9', 'fin13_1d', 'fin14_2_China', 'fin29c2', 'fin10_1d', 'fin44b', 'remittances', 'fin11g', 'mobileowner', 'fin43e', 'fin14c_2', 'fin14c_2_China', 'fin44c', 'fin44a', 'fin1_1a', 'fin17a1', 'fin13_1c', 'fin29_1', 'fin27c1', 'fin10_1e', 'fin13_1e', 'fin1_1b', 'fin31b1', 'fin10a', 'fin4a', 'fin8b', 'fin10_1c', 'fin31b1_China', 'fin11h', 'fin8a', 'fin42a', 'fin13_1f', 'fin14a1', 'fin14_2', 'fin45_1', 'fin26'}

In [7]:
print(set(df2_thailand.columns) - set(df1_thailand.columns))

{'fin49d', 'con10', 'con2g', 'fin49f', 'fin29', 'con30e', 'fin17e', 'fin11_2', 'con16', 'con2d', 'fin25e2', 'con2b', 'domestic_remittances', 'fin47', 'con3', 'receive_pensions', 'fin14e', 'fin17d', 'fin13f_1', 'fin22h', 'con30a', 'con31a', 'con25', 'con2a', 'con19', 'fin19', 'fin9b', 'fin14d', 'con6', 'con31b', 'con32', 'fh2a', 'fin50', 'con29', 'fin22g', 'con9', 'con30c', 'fin25e3', 'fin22a_1', 'fin18', 'fh1', 'fin44', 'con31c', 'fin49c', 'fin13f', 'con21', 'con27', 'fin24d2', 'con13', 'fin24d1', 'con24', 'fin36a', 'fin41a', 'fin17f', 'fin24c', 'con18', 'con23', 'fin34c', 'internet_use', 'con8', 'con20', 'con30f', 'fin25e4', 'fin36', 'fin17c', 'con22', 'con30h', 'fin21', 'fin15', 'fin27', 'fin31d', 'fin13e', 'fin51', 'fin11_0', 'con14', 'fin46', 'con2f', 'fin22e', 'con15', 'fin48a', 'con26', 'con7', 'fin40', 'fin41', 'con31g', 'fin24d3', 'fin26b', 'con11', 'fin39c', 'urbanicity', 'fin48f', 'fin48e', 'con28', 'fin13_1', 'con31e', 'fin22f', 'dig_account', 'con5', 'con30d', 'fin49b', 'fin48d', 'fin49a', 'fin3', 'fin43c', 'fin26a', 'con31h', 'con17', 'con31d', 'fin49e', 'con1', 'fin48b', 'fin25e1', 'con31f', 'con4', 'con2c', 'fin48c', 'con30g', 'fin23', 'con2e', 'con12', 'fin22d', 'fh2', 'con30b'}

### Variables exist in both datasets

In [8]:
common_columns = list(set(df1.columns) & set(df2.columns)) 
print(len(common_columns))
print(common_columns)

76
['inc_q', 'fin33', 'fin11b', 'anydigpayment', 'fin37', 'fin11_1', 'fin22b', 'fin13d', 'educ', 'economycode', 'fin43d', 'receive_wages', 'pay_utilities', 'fin35', 'female', 'age', 'fin13b', 'fin4', 'fin42', 'account_fin', 'fin16', 'fin11e', 'emp_in', 'fin8', 'fin5', 'wgt', 'merchantpay_dig', 'fin28', 'fin11d', 'receive_agriculture', 'fin39a', 'fin39d', 'pop_adult', 'fin39b', 'fin11a', 'fin45', 'fin32', 'fin22c', 'borrowed', 'fin24a', 'fin34b', 'fin24b', 'year', 'account', 'fin34a', 'account_mob', 'fin31b', 'fin2', 'fin43a', 'fin31a', 'economy', 'fin20', 'fin31c', 'regionwb', 'fin13c', 'fin34d', 'fin10', 'fin14c', 'fin17b', 'fin14a', 'fin11f', 'fin6', 'fin30', 'fin9a', 'wpid_random', 'fin22a', 'fin13a', 'fin14b', 'receive_transfers', 'fin17a', 'fin38', 'fin24', 'fin43b', 'saved', 'fin11c', 'fin7']

In [9]:
df_thai = pd.concat([df1_thailand, df2_thailand], ignore_index=True, sort=False)
print(df_thai.shape)
print(df_thai['year'].value_counts())

(2017, 251)
year
2021    1017
2024    1000
Name: count, dtype: int64

In [10]:
df_common = df_thai[common_columns].copy()
print(df_common.shape)
print(df_common['year'].value_counts())

(2017, 76)
year
2021    1017
2024    1000
Name: count, dtype: int64

In [11]:
print(df_common.columns)

Index(['inc_q', 'fin33', 'fin11b', 'anydigpayment', 'fin37', 'fin11_1',
       'fin22b', 'fin13d', 'educ', 'economycode', 'fin43d', 'receive_wages',
       'pay_utilities', 'fin35', 'female', 'age', 'fin13b', 'fin4', 'fin42',
       'account_fin', 'fin16', 'fin11e', 'emp_in', 'fin8', 'fin5', 'wgt',
       'merchantpay_dig', 'fin28', 'fin11d', 'receive_agriculture', 'fin39a',
       'fin39d', 'pop_adult', 'fin39b', 'fin11a', 'fin45', 'fin32', 'fin22c',
       'borrowed', 'fin24a', 'fin34b', 'fin24b', 'year', 'account', 'fin34a',
       'account_mob', 'fin31b', 'fin2', 'fin43a', 'fin31a', 'economy', 'fin20',
       'fin31c', 'regionwb', 'fin13c', 'fin34d', 'fin10', 'fin14c', 'fin17b',
       'fin14a', 'fin11f', 'fin6', 'fin30', 'fin9a', 'wpid_random', 'fin22a',
       'fin13a', 'fin14b', 'receive_transfers', 'fin17a', 'fin38', 'fin24',
       'fin43b', 'saved', 'fin11c', 'fin7'],
      dtype='object')

In [12]:
df_common.head(10)

,inc_q,fin33,fin11b,anydigpayment,fin37,fin11_1,...,fin38,fin24,fin43b,saved,fin11c,fin7
0,4.0,2.0,NaN,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,NaN,2.0
1,4.0,2.0,NaN,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,NaN,2.0
2,4.0,NaN,NaN,1.0,1.0,NaN,...,2.0,4.0,NaN,1.0,NaN,2.0
3,1.0,NaN,NaN,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,NaN,2.0
4,4.0,NaN,NaN,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,NaN,2.0
5,5.0,2.0,NaN,1.0,1.0,NaN,...,2.0,1.0,NaN,1.0,NaN,1.0
6,1.0,2.0,NaN,1.0,1.0,NaN,...,2.0,5.0,1.0,1.0,NaN,2.0
7,5.0,2.0,NaN,1.0,2.0,NaN,...,2.0,1.0,NaN,1.0,NaN,2.0
8,3.0,1.0,2.0,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,2.0,NaN
9,4.0,2.0,NaN,1.0,1.0,NaN,...,2.0,2.0,NaN,1.0,NaN,1.0