### Global Findex EDA

In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

sns.set(style="whitegrid", context="notebook") 
plt.rcParams['figure.dpi'] = 100 
pd.set_option('display.max_columns', 12)
pd.set_option('display.max_rows', 12)

df1 = pd.read_csv(
    'Findex Raw data_2021 (0521-0223).csv',
    encoding='latin1'
)

df2 = pd.read_csv(
    'Findex Raw Data_2025 (0524-1224).csv',
    encoding='latin1'
)
print(df1.shape)
print(df1.head())

(143887, 128)
       economy economycode    regionwb   pop_adult  wpid_random       wgt  \
0  Afghanistan         AFG  South Asia  22647496.0    144274031  0.716416
1  Afghanistan         AFG  South Asia  22647496.0    180724554  0.497408
2  Afghanistan         AFG  South Asia  22647496.0    130686682  0.650431
3  Afghanistan         AFG  South Asia  22647496.0    142646649  0.991862
4  Afghanistan         AFG  South Asia  22647496.0    199055310  0.554940

   ...  remittances  mobileowner  internetaccess  anydigpayment  \
0  ...          5.0            1               2              1
1  ...          5.0            1               2              0
2  ...          3.0            2               2              0
3  ...          5.0            1               2              0
4  ...          5.0            2               2              0

   merchantpay_dig  year
0              0.0  2021
1              0.0  2021
2              0.0  2021
3              0.0  2021
4              0.0  2021

[5 rows x 128 columns]

In [14]:
df1.head()

,economy,economycode,regionwb,pop_adult,wpid_random,wgt,...,remittances,mobileowner,internetaccess,anydigpayment,merchantpay_dig,year
0,Afghanistan,AFG,South Asia,22647496.0,144274031,0.716416,...,5.0,1,2,1,0.0,2021
1,Afghanistan,AFG,South Asia,22647496.0,180724554,0.497408,...,5.0,1,2,0,0.0,2021
2,Afghanistan,AFG,South Asia,22647496.0,130686682,0.650431,...,3.0,2,2,0,0.0,2021
3,Afghanistan,AFG,South Asia,22647496.0,142646649,0.991862,...,5.0,1,2,0,0.0,2021
4,Afghanistan,AFG,South Asia,22647496.0,199055310,0.554940,...,5.0,2,2,0,0.0,2021

In [15]:
df2.head()

,year,economy,economycode,regionwb,pop_adult,wpid_random,...,fin49c,fin49d,fin49e,fin49f,fin50,fin51
0,2024,Nicaragua,NIC,Latin America & Caribbean (excluding high income),4830854,111111345,...,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,Costa Rica,CRI,Latin America & Caribbean (excluding high income),4118576,111111579,...,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,Mali,MLI,Sub-Saharan Africa (excluding high income),12725942,111112511,...,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Kuwait,KWT,High income,3950546,111113432,...,NaN,NaN,NaN,NaN,1.0,1.0
4,2024,Turkiye,TUR,Europe & Central Asia (excluding high income),66691005,111115194,...,NaN,NaN,NaN,NaN,1.0,2.0

### EDA for Findex_dataset Thailand from 2021 through 2025

In [16]:
print(df1.columns.to_list())
print(df2.columns.to_list())

['economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity_f2f', 'account', 'account_fin', 'account_mob', 'fin1_1a', 'fin1_1b', 'fin2', 'fin4', 'fin4a', 'fin5', 'fin6', 'fin7', 'fin8', 'fin8a', 'fin8b', 'fin9', 'fin9a', 'fin10', 'fin10_1a', 'fin10_1b', 'fin10_1c', 'fin10_1d', 'fin10_1e', 'fin10a', 'fin10b', 'fin11_1', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin11g', 'fin11h', 'fin13_1a', 'fin13_1b', 'fin13_1c', 'fin13_1d', 'fin13_1e', 'fin13_1f', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin14_1', 'fin14_2', 'fin14_2_China', 'fin14a', 'fin14a1', 'fin14b', 'fin14c', 'fin14c_2', 'fin14c_2_China', 'fin16', 'fin17a', 'fin17a1', 'fin17b', 'fin20', 'fin22a', 'fin22b', 'fin22c', 'fin24', 'fin24a', 'fin24b', 'fin26', 'fin27_1', 'fin27c1', 'fin27c2', 'fin28', 'fin29_1', 'fin29c1', 'fin29c2', 'fin30', 'fin31a', 'fin31b', 'fin31b1', 'fin31b1_China', 'fin31c', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34d', 'fin34e', 'fin35', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39d', 'fin39e', 'fin42', 'fin42a', 'fin43a', 'fin43b', 'fin43d', 'fin43e', 'fin44a', 'fin44b', 'fin44c', 'fin44d', 'fin45', 'fin45_1', 'fin45_1_China', 'saved', 'borrowed', 'receive_wages', 'receive_transfers', 'receive_pension', 'receive_agriculture', 'pay_utilities', 'remittances', 'mobileowner', 'internetaccess', 'anydigpayment', 'merchantpay_dig', 'year']
['year', 'economy', 'economycode', 'regionwb', 'pop_adult', 'wpid_random', 'wgt', 'female', 'age', 'educ', 'inc_q', 'emp_in', 'urbanicity', 'account_fin', 'account_mob', 'account', 'dig_account', 'borrowed', 'saved', 'receive_wages', 'receive_transfers', 'receive_pensions', 'receive_agriculture', 'merchantpay_dig', 'pay_utilities', 'domestic_remittances', 'anydigpayment', 'fin2', 'fin3', 'fin4', 'fin5', 'fin6', 'fin7', 'fin8', 'fin9a', 'fin9b', 'fin10', 'fin11_0', 'fin11_1', 'fin11_2', 'fin11a', 'fin11b', 'fin11c', 'fin11d', 'fin11e', 'fin11f', 'fin13_1', 'fin13a', 'fin13b', 'fin13c', 'fin13d', 'fin13e', 'fin13f', 'fin13f_1', 'fin14a', 'fin14b', 'fin14c', 'fin14d', 'fin14e', 'fin15', 'fin16', 'fin17a', 'fin17b', 'fin17c', 'fin17d', 'fin17e', 'fin17f', 'fin18', 'fin19', 'fin20', 'fin21', 'fin22a', 'fin22a_1', 'fin22b', 'fin22c', 'fin22d', 'fin22e', 'fin22f', 'fin22g', 'fin22h', 'fin23', 'fin24', 'fin24a', 'fin24b', 'fin24c', 'fin24d1', 'fin24d2', 'fin24d3', 'fin25e1', 'fin25e2', 'fin25e3', 'fin25e4', 'fin26a', 'fin26b', 'fin27', 'fh1', 'fin28', 'fh2', 'fin29', 'fh2a', 'fin30', 'fin31a', 'fin31b', 'fin31c', 'fin31d', 'fin32', 'fin33', 'fin34a', 'fin34b', 'fin34c', 'fin34d', 'fin35', 'fin36', 'fin36a', 'fin37', 'fin38', 'fin39a', 'fin39b', 'fin39c', 'fin39d', 'fin40', 'fin41', 'fin41a', 'fin42', 'fin43a', 'fin43b', 'fin43c', 'fin43d', 'fin44', 'fin45', 'internet_use', 'con1', 'con2a', 'con2b', 'con2c', 'con2d', 'con2e', 'con2f', 'con2g', 'con3', 'con4', 'con5', 'con6', 'con7', 'con8', 'con9', 'con10', 'con11', 'con12', 'con13', 'con14', 'con15', 'con16', 'con17', 'con18', 'con19', 'con20', 'con21', 'con22', 'con23', 'con24', 'con25', 'con26', 'con27', 'con28', 'con29', 'con30a', 'con30b', 'con30c', 'con30d', 'con30e', 'con30f', 'con30g', 'con30h', 'con31a', 'con31b', 'con31c', 'con31d', 'con31e', 'con31f', 'con31g', 'con31h', 'con32', 'fin46', 'fin47', 'fin48a', 'fin48b', 'fin48c', 'fin48d', 'fin48e', 'fin48f', 'fin49a', 'fin49b', 'fin49c', 'fin49d', 'fin49e', 'fin49f', 'fin50', 'fin51']

In [17]:
# Select Thailand economic data from both datasets 
df1_thailand = df1[df1['economy'] == 'Thailand'].copy()
df2_thailand = df2[df2['economy'] == 'Thailand'].copy() 
df1_thailand.shape, df2_thailand.shape

((1017, 128), (1000, 199))

In [18]:
df1_thailand.head()

,economy,economycode,regionwb,pop_adult,wpid_random,wgt,...,remittances,mobileowner,internetaccess,anydigpayment,merchantpay_dig,year
126862,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,156981272,0.224081,...,1.0,1,1,1,0.0,2021
126863,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,195399987,0.526118,...,1.0,1,1,1,1.0,2021
126864,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,181150505,0.148891,...,1.0,1,1,1,1.0,2021
126865,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,190062572,0.353825,...,5.0,1,1,1,0.0,2021
126866,Thailand,THA,East Asia & Pacific (excluding high income),58246340.0,146919431,0.138057,...,3.0,1,1,1,0.0,2021