### Exploratory Data Analysis for Research Question 3 
- To what extent are demographic characteristics particularly gender, associated with financial inclusion in Thailand, and have these disparities changed between 2021 and 2024?

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

sns.set(style="whitegrid", context="notebook") 
plt.rcParams['figure.dpi'] = 100 
pd.set_option('display.max_columns', 12)
pd.set_option('display.max_rows', 12)

rq3 = pd.read_csv("data_cleaned.csv")

In [3]:
rq3.head(5)

,wage_payment_method,no_account_family_member,debit_card_ownership,ever_had_mobile_money_account,survey_year,ever_had_bank_account,...,received_transfers,no_account_insufficient_funds,codes_found,gender,age_group,education_original
0,2.0,NaN,2.0,2.0,2021,NaN,...,1.0,NaN,False,Female,23_29,3.0
1,2.0,NaN,1.0,1.0,2021,NaN,...,1.0,NaN,False,Male,30_39,3.0
2,NaN,NaN,NaN,2.0,2021,NaN,...,1.0,NaN,False,Female,40_49,3.0
3,NaN,NaN,NaN,2.0,2021,NaN,...,1.0,NaN,False,Female,40_49,3.0
4,NaN,NaN,2.0,1.0,2021,NaN,...,1.0,NaN,False,Male,30_39,3.0

In [5]:
rq3.columns.tolist()

['wage_payment_method',
 'no_account_family_member',
 'debit_card_ownership',
 'ever_had_mobile_money_account',
 'survey_year',
 'ever_had_bank_account',
 'no_account_documentation',
 'borrowed_money',
 'saved_mobile_money',
 'female',
 'account_ownership',
 'credit_card_ownership',
 'received_goverment_transfer',
 'wages_bank_account',
 'mobile_money_transaction',
 'agriculture_payment_method',
 'mobile_money_activity',
 'no_account_distance',
 'age',
 'saved_bank',
 'education_level',
 'received_wages',
 'utility_payment',
 'any_digital_payment',
 'account_transaction_activity',
 'no_mobile_agents_far',
 'emergency_funds',
 'no_account_too_expensive',
 'sent_domestic_remittance_account',
 'merchantpay_dig',
 'store_money_account',
 'income_quintile',
 'utility_payment_cash',
 'agriculture_payment_account',
 'borrowed_from_family_friends',
 'financial_health_indicator',
 'borrowed_from_formal_bank',
 'mobile_money_send_recieve',
 'high_withdrawal_fee_wages',
 'received_acc_balance_info',
 'agri_payment_mobile',
 'economycode',
 'borrowed_from_savings_club',
 'adult_population',
 'received_agriculture_payment',
 'saved_money',
 'utility_payment_mobile',
 'agri_payment_card',
 'mobile_money_usage',
 'agricultural_payment_mobile',
 'agri_payment_bank',
 'wages_mobile',
 'survey_weight',
 'financial_instituion_account',
 'made_utility_payment',
 'emergency_fund_access',
 'recieved_wages',
 'no_account_lack_of_trust',
 'account_ownership.1',
 'debit_card_ownership.1',
 'account_usage',
 'no_mobile_account_too_expensive',
 'respondent_id',
 'world_bank_region',
 'emergency_fund_source',
 'no_mobile_account_lack_documentation',
 'applied_for_mobile_loan',
 'wages_card',
 'received_public_pension',
 'recieved_agricultural_payment',
 'utility_payment_bank',
 'employment_status',
 'mobile_money_account',
 'economy',
 'received_transfers',
 'no_account_insufficient_funds',
 'codes_found',
 'gender',
 'age_group',
 'education_original']

### Financial Inclusion Dimension

### Demographics & socioeconomics indicators

In [ ]:
demographics = rq3["age", "gender", "income_quintile", "education_level", "survey_year", "employment_status"]

### Access and Ownership

- Access and Ownership: Does the person have access to formal/digital financial infrastructure?

In [6]:
acc_own = rq3[["account_ownership", 
            "financial_instituion_account", 
            "mobile_money_account",
            "debit_card_ownership",
            "credit_card_ownership"]] 
acc_own.head()

,account_ownership,financial_instituion_account,mobile_money_account,debit_card_ownership,credit_card_ownership
0,1,1,1.0,2.0,1.0
1,1,1,1.0,1.0,1.0
2,1,1,1.0,NaN,1.0
3,1,1,1.0,NaN,1.0
4,1,1,0.0,2.0,1.0

### Usage

- Does the person actually use financial services?

In [7]:
acc_usage = rq3[["account_usage",
                "account_transaction_activity",
                "any_digital_payment",
                "mobile_money_activity",
                "mobile_money_usage",
                "mobile_money_transaction",
                "merchantpay_dig",
                "made_utility_payment"]]

### Saving and Borrowing 
- Can people use the financial system for saving and borrowing?

In [8]:
saving_borrow = rq3[["saved_money",
                    "saved_bank",
                    "saved_mobile_money",
                    "borrowed_money",
                    "borrowed_from_formal_bank",
                    "borrowed_from_family_friends",
                    "borrowed_from_savings_club"]]